### ISSUE TITLE
import adafruit_circuitplayground.express from an imported file fails

### ISSUE THREAD

**Issue by dmopalmer** [adafruit/Adafruit_CircuitPython_CircuitPlayground#80]
With a file `testme.py` which consists of the single import statement:
```
import adafruit_circuitplayground.express
```
I get a maximum recursion depth error:
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-beta.0 on 2019-11-19; Adafruit CircuitPlayground Express with samd21g18
>>> import testme
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "testme.py", line 1, in <module>
  File "adafruit_circuitplayground/express.py", line 699, in <module>
  File "adafruit_circuitplayground/express.py", line 127, in __init__
  File "adafruit_lis3dh.py", line 321, in __init__
  File "adafruit_lis3dh.py", line 100, in __init__
  File "adafruit_lis3dh.py", line 126, in data_rate
  File "adafruit_lis3dh.py", line 300, in _read_register_byte
  File "adafruit_lis3dh.py", line 325, in _read_register
RuntimeError: maximum recursion depth exceeded
>>> 
```

I get this on the latest version 4.1.2 and version 5.0.0-beta.2 as well, although those don't dump the stack trace, but crash and then complain on the next reboot that the stack was corrupted. 

This is with the lib directory empty.  

Doing the same `import adafruit_circuitplayground.express` from the command line  has no problems.
Doing that import from the command line and then `import testme` also works fine.

I tried this on two different Circuit Playground Express hardware units.

**Comment by dhalbert** [comment]
We thought we increased the stack size enough to handle this, since we saw it ourselves. But we had a `code.py` that included:

```python
from adafruit_circuitplayground import cp
```
which works on either CPX or CPB.

We'll see about increasing it more to handle the case you mention. Thanks for this.

**Comment by dmopalmer** [comment]
Importing it from `code.py` or `main.py` works.  However, I want to develop something with a name like `myprogram.py` (which in turn imports cpx) and then having `main.py` be just `import myprogram`.  (That way I can have different versions or other things and don't have to worry about which of my actual programs is currently called `main.py`.)

A quick workaround is to have `code.py` be:
```
from adafruit_circuitplayground.express import cpx
import myprogram
```
and to likewise manually import cpx before importing myprogram when doing it from the REPL.
