### ISSUE TITLE
dir(cp) doesn't work

### ISSUE THREAD

**Issue by ajs256** [adafruit/Adafruit_CircuitPython_CircuitPlayground#98]
```
>>> from adafruit_circuitplayground import cp
>>> dir(cp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_circuitplayground/express.py", line 82, in _unsupported
NotImplementedError: This feature is not supported on Circuit Playground Express.
>>> import math # to check that dir() works on something else
>>> dir(math)
['__class__', '__name__', 'acos', 'asin', 'atan', 'atan2', 'ceil', 'copysign', 'cos', 'degrees', 'e', 'exp', 'fabs', 'floor', 'fmod', 'frexp', 'isfinite', 'isinf', 'isnan', 'ldexp', 'log', 'modf', 'pi', 'pow', 'radians', 'sin', 'sqrt', 'tan', 'trunc']
```
I am not sure why this is happening. `cp` imports correctly, but `dir(cp)` doesn't work.

**Comment by tannewt** [comment]
This is a weird artifact of how dir works internally. It's trying to read a property that isn't implemented on CPX. It's non-trivial to make dir not do this internally.
